from crew_tools._config import Config, load_config
from crew_tools._logging import LoggerMixin, get_logger, request_id, setup_logging
from crew_tools._plugins import ToolPlugin, discover_plugins, load_plugins
from crew_tools._version import __version__
from crew_tools.async_tools import async_calculate, async_convert, async_word_counter
from crew_tools.calculator import (
    calculate_safe,
    calculate_v1,
    calculate_v2,
    calculate_v3,
    calculate_v4,
    calculate_v5,
)
from crew_tools.chart_tools import (
    create_bar_chart,
    create_histogram,
    create_line_chart,
    create_pie_chart,
)
from crew_tools.code_tools import format_code, run_python, validate_json
from crew_tools.crypto_tools import (
    base64_decode,
    base64_encode,
    hash_string,
    random_password,
)
from crew_tools.data_tools import aggregate_data, describe_data, filter_rows, sort_rows
from crew_tools.file_tools import (
    csv_to_json,
    json_to_csv,
    list_dir,
    read_file,
    write_file,
)
from crew_tools.format_tools import (
    json_prettify,
    toml_parse,
    xml_parse,
    yaml_dump,
    yaml_parse,
)
from crew_tools.memory_tools import (
    session_clear,
    session_get,
    session_list,
    session_set,
)
from crew_tools.network_tools import dns_lookup, http_status, port_check
from crew_tools.production import (
    RateLimiter,
    ToolCache,
    async_batch_process,
    batch_process,
    with_retry,
)
from crew_tools.report_tools import html_table, markdown_table, word_wrap
from crew_tools.safe_converter import convert_safe
from crew_tools.safe_word_counter import word_counter_advanced, word_counter_safe
from crew_tools.stats_tools import basic_stats, moving_average, outliers, percentile
from crew_tools.system_tools import env_get, os_info, system_info, which_program
from crew_tools.template_tools import (
    diff_text,
    regex_replace,
    regex_search,
    render_template,
)
from crew_tools.text_tools import count_sentences, reading_time, text_stats
from crew_tools.time_tools import (
    current_time,
    format_date,
    parse_date,
    timezone_convert,
)
from crew_tools.unit_converter import convert_v1, convert_v2, convert_v3, convert_v4
from crew_tools.validator import (
    validate_email,
    validate_phone,
    validate_url,
    validate_v2,
)
from crew_tools.web_tools import rss_parse, web_fetch, web_search
from crew_tools.word_counter import (
    word_counter_v1,
    word_counter_v2,
    word_counter_v3,
    word_counter_v4,
)

__all__ = [
    "TOOL_REGISTRY",
    "Config",
    "LoggerMixin",
    "RateLimiter",
    "ToolCache",
    "ToolPlugin",
    "__version__",
    "aggregate_data",
    "async_batch_process",
    "async_calculate",
    "async_convert",
    "async_word_counter",
    "base64_decode",
    "base64_encode",
    "basic_stats",
    "batch_process",
    "calculate_safe",
    "calculate_v1",
    "calculate_v2",
    "calculate_v3",
    "calculate_v4",
    "calculate_v5",
    "convert_safe",
    "convert_v1",
    "convert_v2",
    "convert_v3",
    "convert_v4",
    "count_sentences",
    "create_bar_chart",
    "create_histogram",
    "create_line_chart",
    "create_pie_chart",
    "csv_to_json",
    "current_time",
    "describe_data",
    "diff_text",
    "discover_plugins",
    "dns_lookup",
    "env_get",
    "filter_rows",
    "format_code",
    "format_date",
    "get_logger",
    "hash_string",
    "html_table",
    "http_status",
    "json_prettify",
    "json_to_csv",
    "list_dir",
    "load_config",
    "load_plugins",
    "markdown_table",
    "moving_average",
    "os_info",
    "outliers",
    "parse_date",
    "percentile",
    "port_check",
    "random_password",
    "read_file",
    "reading_time",
    "regex_replace",
    "regex_search",
    "render_template",
    "request_id",
    "rss_parse",
    "run_python",
    "session_clear",
    "session_get",
    "session_list",
    "session_set",
    "setup_logging",
    "sort_rows",
    "system_info",
    "text_stats",
    "timezone_convert",
    "toml_parse",
    "validate_email",
    "validate_json",
    "validate_phone",
    "validate_url",
    "validate_v2",
    "web_fetch",
    "web_search",
    "which_program",
    "with_retry",
    "word_counter_advanced",
    "word_counter_safe",
    "word_counter_v1",
    "word_counter_v2",
    "word_counter_v3",
    "word_counter_v4",
    "word_wrap",
    "write_file",
    "xml_parse",
    "yaml_dump",
    "yaml_parse",
]

TOOL_REGISTRY = {
    "word_counter_v1": word_counter_v1,
    "word_counter_v2": word_counter_v2,
    "word_counter_v3": word_counter_v3,
    "word_counter_v4": word_counter_v4,
    "word_counter_safe": word_counter_safe,
    "word_counter_advanced": word_counter_advanced,
    "convert_v1": convert_v1,
    "convert_v2": convert_v2,
    "convert_v3": convert_v3,
    "convert_v4": convert_v4,
    "convert_safe": convert_safe,
    "calculate_v1": calculate_v1,
    "calculate_v2": calculate_v2,
    "calculate_v3": calculate_v3,
    "calculate_v4": calculate_v4,
    "calculate_v5": calculate_v5,
    "calculate_safe": calculate_safe,
    "validate_email": validate_email,
    "validate_url": validate_url,
    "validate_phone": validate_phone,
    "validate_v2": validate_v2,
    "count_sentences": count_sentences,
    "reading_time": reading_time,
    "text_stats": text_stats,
    "async_word_counter": async_word_counter,
    "async_convert": async_convert,
    "async_calculate": async_calculate,
    "web_fetch": web_fetch,
    "web_search": web_search,
    "rss_parse": rss_parse,
    "read_file": read_file,
    "write_file": write_file,
    "list_dir": list_dir,
    "csv_to_json": csv_to_json,
    "json_to_csv": json_to_csv,
    "describe_data": describe_data,
    "filter_rows": filter_rows,
    "sort_rows": sort_rows,
    "aggregate_data": aggregate_data,
    "run_python": run_python,
    "format_code": format_code,
    "validate_json": validate_json,
    "render_template": render_template,
    "regex_search": regex_search,
    "regex_replace": regex_replace,
    "diff_text": diff_text,
    "parse_date": parse_date,
    "format_date": format_date,
    "timezone_convert": timezone_convert,
    "current_time": current_time,
    "hash_string": hash_string,
    "base64_encode": base64_encode,
    "base64_decode": base64_decode,
    "random_password": random_password,
    "system_info": system_info,
    "which_program": which_program,
    "env_get": env_get,
    "os_info": os_info,
    "session_set": session_set,
    "session_get": session_get,
    "session_list": session_list,
    "session_clear": session_clear,
    "create_bar_chart": create_bar_chart,
    "create_line_chart": create_line_chart,
    "create_pie_chart": create_pie_chart,
    "create_histogram": create_histogram,
    "yaml_parse": yaml_parse,
    "yaml_dump": yaml_dump,
    "toml_parse": toml_parse,
    "xml_parse": xml_parse,
    "json_prettify": json_prettify,
    "dns_lookup": dns_lookup,
    "port_check": port_check,
    "http_status": http_status,
    "basic_stats": basic_stats,
    "moving_average": moving_average,
    "percentile": percentile,
    "outliers": outliers,
    "markdown_table": markdown_table,
    "html_table": html_table,
    "word_wrap": word_wrap,
}
