# -*- coding: utf-8 -*-
"""Leonardo_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10MpCE27u_LDZuc53PStODxo6WNavKC0f
"""

Leonardo...

1. CINEMATIC POSTER

cyberpunk warrior standing in rainy neon street,
low angle,
cinematic lighting,
movie poster style,
sharp focus,
highly detailed

2. FANTASY KNIGHT
epic knight holding glowing sword,
volumetric lighting,
dark fantasy,
wide angle,
concept art,
highly detailed

3. REALISTIC PORTRAIT
young man wearing black jacket,
close up portrait,
golden hour lighting,
85mm lens,
RAW photo,
photorealistic

4. PRODUCT AD
luxury gaming headphones on reflective black table,
studio lighting,
product photography,
macro details,
sharp focus

5. ANIME STREET SCENE
anime girl walking through rainy Tokyo alley,
blue hour lighting,
anime style,
vivid colors,
cinematic atmosphere

7. FASHION SHOOT
luxury fashion model in Paris street,
editorial photography,
soft box lighting,
professional photography,
sharp focus

8. POST APOCALYPTIC CITY
destroyed futuristic city after war,
bird's eye view,
dramatic lighting,
volumetric smoke,
cinematic atmosphere

9. SPACE ART
astronaut standing on alien planet,
centered composition,
surreal atmosphere,
cinematic lighting,
concept art

11. Luxury Watch Macro Shot
luxury wrist watch close up,
macro photography,
premium metallic details,
studio lighting,
sharp reflections,
black background,
ultra detailed,
elegant luxury advertisement,
realistic textures,
professional product photography

13. Cyberpunk Motorcycle Racing
cyberpunk motorcycle racing through neon city streets,
dynamic camera angle,
neon lights,
wet reflective roads,
motion blur,
futuristic atmosphere,
high speed action,
cinematic lighting,
vibrant colors,
detailed cyberpunk environment

15. Snowy Village at Night
beautiful snowy village at night,
soft moonlight,
warm glowing windows,
cinematic winter atmosphere,
snow covered rooftops,
quiet fantasy town,
detailed environment,
cozy lighting,
high quality,
dreamlike mood

16. Dark Knight in Storm
dark knight riding horse through storm,
dramatic lighting,
dark fantasy atmosphere,
heavy rain,
lightning in sky,
cinematic shadows,
flowing black cape,
epic battlefield mood,
high detail armor,
powerful cinematic composition

18. Luxury Perfume Product Shot
luxury perfume bottle on reflective surface,
studio lighting,
premium product photography,
glass reflections,
minimal elegant background,
soft shadows,
gold accents,
ultra detailed,
commercial advertisement style,
high realism

19. Anime Swordsman Portrait
anime swordsman close up portrait,
rim lighting,
vivid colors,
sharp anime eyes,
flowing hair,
cinematic shadows,
detailed armor,
dramatic anime atmosphere,
high detail illustration,
epic character art

20. Futuristic Luxury Bedroom
futuristic luxury bedroom interior,
soft diffused lighting,
modern architectural visualization,
large glass windows,
minimal elegant design,
ambient lighting,
premium materials,
clean futuristic atmosphere,
ultra detailed interior,
cinematic realism

ancient dragon flying above fantasy kingdom,
epic fantasy poster,
god rays,
volumetric lighting,
dramatic clouds,
cinematic atmosphere,
detailed castle,
golden hour lighting,
high fantasy artwork

powerful mage casting magical energy,
volumetric lighting,
floating particles,
ancient robes,
mystical atmosphere,
blue magical glow,
fantasy concept art,
cinematic composition

dark villain sitting on throne,
dramatic shadows,
red glowing eyes,
dark fantasy atmosphere,
cinematic lighting,
volumetric smoke,
detailed black armor,
powerful cinematic composition

modern smartphone floating in futuristic environment,
soft cinematic lighting,
clean reflections,
minimal premium design,
technology advertisement style,
high detail render,
professional product showcase

female warrior standing in grassy field,
golden hour lighting,
warm sunlight,
cinematic atmosphere,
soft orange glow,
detailed armor,
volumetric dust,
realistic portrait,
professional composition

cyberpunk hacker portrait close up,
neon lighting,
detailed face,
cinematic shadows,
blue and pink glow,
shallow depth of field,
professional portrait photography

cyberpunk hacker standing in massive futuristic city,
wide angle composition,
neon lights,
rain reflections,
cinematic atmosphere,
large environment scale,
dynamic perspective

anime swordsman with glowing katana,
rim lighting,
vivid anime colors,
dynamic pose,
cinematic rain,
detailed anime illustration,
epic anime atmosphere

realistic samurai holding glowing katana,
cinematic lighting,
wet realistic armor,
rain atmosphere,
high detail skin textures,
dramatic shadows,
photorealistic cinematic scene

warrior walking through burning battlefield,
cinematic lighting,
dramatic smoke,
movie color grading,
realistic atmosphere,
high contrast shadows,
epic composition

fantasy warrior walking through magical battlefield,
god rays,
volumetric lighting,
floating magical particles,
epic fantasy atmosphere,
glowing sword,
high fantasy artwork

futuristic soldier portrait,
rim lighting,
bright edge glow,
dark background,
cinematic shadows,
detailed armor,
heroic composition,
high contrast lighting

futuristic soldier standing before massive sunset,
backlit silhouette,
strong light behind subject,
cinematic atmosphere,
dust particles,
dramatic environment,
epic mood

young woman walking through sunny city street,
natural lighting,
soft daylight,
realistic atmosphere,
casual fashion,
professional photography

fantasy knight with glowing armor,
magical energy effects,
god rays,
epic fantasy atmosphere,
stylized cinematic artwork