# -*- coding: utf-8 -*-
"""Bing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mhT6Rt_Kb-pWWITwWNZZ2UaXkhCHlEG
"""

Bing....

1. GOLDEN HOUR PORTRAIT
beautiful Indian woman smiling in sunflower field,
close up portrait,
golden hour lighting,
85mm lens,
RAW photo,
soft bokeh background,
photorealistic,
professional photography

2. CYBERPUNK CITY
futuristic cyberpunk Tokyo street at night,
neon lights,
rain reflections,
street photography,
35mm film,
cinematic atmosphere,
wide angle,
ultra detailed

3. FANTASY WARRIOR
epic fantasy warrior holding glowing sword,
low angle,
volumetric lighting,
god rays,
dark fantasy,
concept art,
masterpiece

4. STUDIO FASHION SHOOT
luxury fashion model in black suit,
editorial photography,
studio lighting,
sharp focus,
DSLR,
award winning

5. MOONLIGHT FOREST
mysterious forest under moonlight,
fog atmosphere,
cinematic lighting,
wide angle,
dark fantasyq

6. PRODUCT PHOTOGRAPHY
luxury gaming headphones on reflective table,
product photography,
studio lighting,
macro details,
professional photography,
8k

7. ANIME STREET
anime girl walking in rainy neon alley,
blue hour lighting,
Studio Ghibli style,
vivid colors,
cinematic

8. POST APOCALYPSE
destroyed futuristic city after war,
bird's eye view,
dramatic lighting,
volumetric smoke,
cinematic atmosphere

9. DRAGON SCENE
massive dragon flying over volcano,
wide angle,
god rays,
dark fantasy,
cinematic lighting

powerful superhero landing on destroyed city street,
movie poster,
low angle,
cinematic lighting,
dramatic smoke,
dynamic composition,
backlit,
sharp focus,
hyperrealistic,
award winning,
8k

anime swordsman with glowing blue eyes,
dynamic angle,
blue hour lighting,
anime style,
vivid colors,
cinematic atmosphere

luxury perfume bottle with soft reflections,
studio lighting,
product photography,
clean background,
photorealistic

futuristic smartphone floating in dark studio,
rim lighting,
product photography,
sharp reflections,
highly detailed

luxury silver watch close up,
macro photography,
studio lighting,
sharp focus,
professional photography

mysterious warrior standing in dark forest,
moonlight,
soft fog,
cinematic lighting,
dark fantasy,
sharp focus

young man wearing black jacket,
close up portrait,
golden hour lighting,
85mm lens,
RAW photo,
DSLR

cyberpunk assassin walking through rainy neon street,
cinematic lighting,
dynamic angle,
movie atmosphere,
film grain,
highly detailed

young man walking in modern city street,
natural lighting,
street photography,
RAW photo,
DSLR,
photorealistic

futuristic luxury skyscraper beside ocean,
wide angle,
Realistic,
structuered,
modern architecture concept,
soft lighting,
glass reflections,
highly detailed

abandoned hospital hallway at midnight,
moonlight,
harsh shadows,
fog atmosphere,
cinematic horror lighting,
dark fantasy

macro photography of water droplets on green leafs,
natural lighting,
sharp focus,
ultra detailed,
photorealistic

