from langgraph.graph import (
    StateGraph,
    START,
    END
)

from state.state import WorkflowState


# --------------------------------
# Draft Node
# --------------------------------

def draft_node(
    state: WorkflowState
):

    topic = state["topic"]

    draft = f"""
Article Title: {topic}

AI Agents are intelligent systems.

Generated by Draft Node.
"""

    return {
        "draft": draft
    }


# --------------------------------
# AI Review
# --------------------------------

def review_node(
    state: WorkflowState
):

    return {
        "review_notes":
            "AI Review Passed.",
        "reviewed": True
    }


# --------------------------------
# Human Review
# --------------------------------

def human_review_node(
    state: WorkflowState
):

    print("\n")
    print("=" * 50)
    print("HUMAN REVIEW")
    print("=" * 50)

    print(state["draft"])

    print("\n")

    feedback = input(
        "Feedback: "
    )

    decision = input(
        "Approve? (y/n): "
    )

    approved = (
        decision.lower() == "y"
    )

    return {
        "human_feedback": feedback,
        "human_approved": approved
    }


# --------------------------------
# Revise Node
# --------------------------------

def revise_node(
    state: WorkflowState
):

    revised_draft = (
        state["draft"]
        + f"\n\n[REVISION]\n"
        + state["human_feedback"]
    )

    return {
        "draft": revised_draft,
        "revision_count":
            state["revision_count"] + 1
    }


# --------------------------------
# Publish Node
# --------------------------------

def publish_node(
    state: WorkflowState
):

    with open(
        "outputs/final.md",
        "w",
        encoding="utf-8"
    ) as file:

        file.write(
            state["draft"]
        )

    print(
        "\nPublished Successfully!"
    )

    return {
        "published": True
    }


# --------------------------------
# Router
# --------------------------------

def approval_router(
    state: WorkflowState
):

    if state["human_approved"]:

        return "publish"

    return "revise"


# --------------------------------
# Graph
# --------------------------------

workflow = StateGraph(
    WorkflowState
)

workflow.add_node(
    "draft",
    draft_node
)

workflow.add_node(
    "review",
    review_node
)

workflow.add_node(
    "human_review",
    human_review_node
)

workflow.add_node(
    "revise",
    revise_node
)

workflow.add_node(
    "publish",
    publish_node
)

workflow.add_edge(
    START,
    "draft"
)

workflow.add_edge(
    "draft",
    "review"
)

workflow.add_edge(
    "review",
    "human_review"
)

workflow.add_conditional_edges(
    "human_review",
    approval_router,
    {
        "publish": "publish",
        "revise": "revise"
    }
)

workflow.add_edge(
    "revise",
    "human_review"
)

workflow.add_edge(
    "publish",
    END
)

app = workflow.compile()